// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wlogbwxjteyycddkjvki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indsb2did3hqdGV5eWNkZGtqdmtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc1NjMxNzUsImV4cCI6MjA1MzEzOTE3NX0.WFbZf1i8uryefHaauMbiWh7G8993fATpzIq-o9fnIrc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);